### ISSUE TITLE
Webm support and etc

### ISSUE THREAD

**Issue by izua** [smugdev/smugboard#1]
Currently there is no Webm/mp4 support and some other formats.
Formats that could be added in the future: webm, mp4, mp3, ogg, flac, and apng.

**Comment by smugdev** [comment]
Implemented with https://github.com/smugdev/smugboard/commit/0a1d89c41a595131304b7d9eb6beac623b56e29a

Embedding a vichan-style player in the page will happen later, for now webms will show up as links.

**Comment by smugdev** [comment]
Note that smugchan won't support these uploads until I get around to upgrading the live install, which should happen within the next few days.

**Comment by smugdev** [comment]
Note that the smugchan live instance won't support these uploads until I get around to upgrading it, which should happen within the next few days.
